name: 'Add existing app or test app'

run-name: "Add existing app or test app in [${{ github.ref_name }}]"

on:
  workflow_dispatch:
    inputs:
      project:
        description: Project name if the repository is setup for multiple projects
        required: false
        default: '.'
      url:
        description: Direct Download Url of .app or .zip file
        required: true
      directCommit:
        description: Direct COMMIT (Y/N)
        required: false
        default: 'N'
      useGhTokenWorkflow:
        description: Use GhTokenWorkflow for Pull Request/COMMIT
        type: boolean
      tempGhTokenWorkflow:
        description: Temporary Personal Access Token to use as GhTokenWorkflow
        required: false
        default: ''

permissions:
  contents: write
  pull-requests: write

defaults:
  run:
    shell: pwsh

env:
  ALGoOrgSettings: ${{ vars.ALGoOrgSettings }}
  ALGoRepoSettings: ${{ vars.ALGoRepoSettings }}

jobs:
  AddExistingAppOrTestApp:
    runs-on: [ ubuntu-latest ]
    steps:
      - name: Mask Token
        id: tempGhTokenWorkflow
        run: |
          $eventPath = Get-Content -Encoding UTF8 -Path $env:GITHUB_EVENT_PATH -Raw | ConvertFrom-Json
          $tempGhTokenWorkflow = $eventPath.inputs.tempGhTokenWorkflow
          if ($tempGhTokenWorkflow) {
            Write-Host "::add-mask::$tempGhTokenWorkflow"
            $tempGhTokenWorkflow = [Convert]::ToBase64String([System.Text.Encoding]::UTF8.GetBytes($tempGhTokenWorkflow))
            Write-Host "::add-mask::$tempGhTokenWorkflow"
          }
          Add-Content -Encoding UTF8 -Path $ENV:GITHUB_OUTPUT -Value "tempGhTokenWorkflow=$tempGhTokenWorkflow"

      - name: Checkout
        uses: actions/checkout@v3

      - name: Initialize the workflow
        id: init
        uses: freddydk/AL-Go/Actions/WorkflowInitialize@temptoken
        with:
          shell: pwsh
          eventId: "DO0090"

      - name: Read settings
        uses: freddydk/AL-Go/Actions/ReadSettings@temptoken
        with:
          shell: pwsh

      - name: Read secrets
        id: ReadSecrets
        uses: freddydk/AL-Go/Actions/ReadSecrets@temptoken
        with:
          shell: pwsh
          gitHubSecrets: ${{ toJson(secrets) }}
          getSecrets: 'TokenForPush'
          tempGhTokenWorkflow: ${{ steps.tempGhTokenWorkflow.outputs.tempGhTokenWorkflow }}
          useGhTokenWorkflowForPush: '${{ github.event.inputs.useGhTokenWorkflow }}'

      - name: Add existing app
        uses: freddydk/AL-Go/Actions/AddExistingApp@temptoken
        with:
          shell: pwsh
          token: ${{ steps.ReadSecrets.outputs.TokenForPush }}
          parentTelemetryScopeJson: ${{ steps.init.outputs.telemetryScopeJson }}
          project: ${{ github.event.inputs.project }}
          url: ${{ github.event.inputs.url }}
          directCommit: ${{ github.event.inputs.directCommit }}

      - name: Finalize the workflow
        if: always()
        uses: freddydk/AL-Go/Actions/WorkflowPostProcess@temptoken
        with:
          shell: pwsh
          eventId: "DO0090"
          telemetryScopeJson: ${{ steps.init.outputs.telemetryScopeJson }}
