name: 'Create a new app'

run-name: "Create a new app in [${{ github.ref_name }}]"

on:
  workflow_dispatch:
    inputs:
      project:
        description: Project name if the repository is setup for multiple projects
        required: false
        default: '.'
      name:
        description: Name
        required: true      
      publisher:
        description: Publisher
        required: true
      idrange:
        description: ID range (from..to)
        required: true
      sampleCode:
        description: Include Sample code (Y/N)
        required: false
        default: 'Y'
      directCommit:
        description: Direct COMMIT (Y/N)
        required: false
        default: "N"
      useGhTokenWorkflow:
        description: Use GhTokenWorkflow for Pull Request/COMMIT
        type: boolean

permissions:
  contents: write
  pull-requests: write

defaults:
  run:
    shell: pwsh

env:
  ALGoOrgSettings: ${{ vars.ALGoOrgSettings }}
  ALGoRepoSettings: ${{ vars.ALGoRepoSettings }}

jobs:
  CreateApp:
    runs-on: [ ubuntu-latest ]
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Initialize the workflow
        id: init
        uses: freddydk/AL-Go/Actions/WorkflowInitialize@OnlyNeededSecrets
        with:
          shell: pwsh
          eventId: "DO0092"

      - name: Read settings
        uses: freddydk/AL-Go/Actions/ReadSettings@OnlyNeededSecrets
        with:
          shell: pwsh
          parentTelemetryScopeJson: ${{ steps.init.outputs.telemetryScopeJson }}
          get: type

      - name: Read GitHub secrets
        if: github.event.inputs.useGhTokenWorkflow == 'true'
        id: readGitHubSecrets
        env:
          getSecrets: 'ghTokenWorkflow'
        run: |
          $gitHubSecrets = '${{ toJson(secrets) }}' | ConvertFrom-Json
          $settings = $env:settings | ConvertFrom-Json
          $secrets = @{}
          $env:getSecrets.Split(',') | ForEach-Object {
            $secretName = $_
            if ($settings.PSObject.Properties.Name -eq "$($secretName)SecretName") { $secretName = $settings."$($secretName)SecretName" }
            if ($secretName -and $gitHubSecrets.PSObject.Properties.Name -eq $secretName) {
              $secrets += @{ $secretName = $gitHubSecrets."$secretName" }
            }
          }
          Add-Content -Path $env:GITHUB_OUTPUT -Value "gitHubSecrets=$($secrets | ConvertTo-Json -compress)"

      - name: Read secrets
        uses: freddydk/AL-Go/Actions/ReadSecrets@OnlyNeededSecrets
        if: github.event.inputs.useGhTokenWorkflow == 'true'
        env:
          secrets: ${{ steps.readGitHubSecrets.outputs.gitHubSecrets }}
        with:
          shell: pwsh
          parentTelemetryScopeJson: ${{ steps.init.outputs.telemetryScopeJson }}
          getSecrets: 'ghTokenWorkflow'

      - name: CalculateToken
        id: CalculateToken
        env:
          useGhTokenWorkflow: ${{ github.event.inputs.useGhTokenWorkflow }}
        run: |
          if ($env:useGhTokenWorkflow -eq 'true') {
            $ghToken = [System.Text.Encoding]::UTF8.GetString([System.Convert]::FromBase64String($env:GHTOKENWORKFLOW))
          } else {
            $ghToken = '${{ secrets.GITHUB_TOKEN }}'
          }
          Add-Content -Encoding UTF8 -Path $env:GITHUB_OUTPUT -Value "ghToken=$ghToken"

      - name: Creating a new app
        uses: freddydk/AL-Go/Actions/CreateApp@OnlyNeededSecrets
        with:
          shell: pwsh
          token: ${{ steps.CalculateToken.outputs.ghToken }}
          parentTelemetryScopeJson: ${{ steps.init.outputs.telemetryScopeJson }}
          project: ${{ github.event.inputs.project }}
          type: ${{ env.type }}
          name: ${{ github.event.inputs.name }}
          publisher: ${{ github.event.inputs.publisher }}
          idrange: ${{ github.event.inputs.idrange }}
          sampleCode: ${{ github.event.inputs.sampleCode }}
          directCommit: ${{ github.event.inputs.directCommit }}

      - name: Finalize the workflow
        if: always()
        uses: freddydk/AL-Go/Actions/WorkflowPostProcess@OnlyNeededSecrets
        with:
          shell: pwsh
          eventId: "DO0092"
          telemetryScopeJson: ${{ steps.init.outputs.telemetryScopeJson }}
