name: 'Pull Request Handler'

on:
  pull_request:
    paths-ignore:
      - '**.md'
    branches: [ 'main' ]

defaults:
  run:
    shell: PowerShell

permissions:
  contents: read
  actions: read
  pull-requests: read

jobs:
  PullRequestHandler:
    runs-on: [ windows-latest ]
    steps:
      - name: Start CI/CD workflow
        run: |
          Write-Host "CI/CD workflow will start upon completion of this workflow"
