name: 'Pull Request Handler'

on:
  pull_request:
    paths-ignore:
      - '**.md'
    branches: [ 'main' ]

defaults:
  run:
    shell: PowerShell

permissions:
  contents: read
  actions: read
  pull-requests: read

  PullRequestHandler:
    runs-on: [ windows-latest ]
    steps:
      - name: Wait for CI/CD to start
        run: |
          Start-Sleep -seconds 50
